### ISSUE TITLE
Broken Zotero group link on "Our Story -> History"

### ISSUE THREAD

**Issue by dhowlett1692** [chnm/rrchnm-wordpress#67]
https://rrchnm.org/our-story/history/
The link at the bottom to Writings about RRCHNM (Zotero group) is broken
Our Founder link on the left hand menu and Thanks, Roy at the bottom both link to the same place. Do we need both?

**Comment by kimisgold** [comment]
I don't think it hurts to have the "Thanks, Roy" archive in two different places—they're pretty far from each other on the page and contextualized for somewhat different usages.

The broken Zotero group is an issue though.

**Comment by kimisgold** [comment]
I've found the CHNM Zotero group: https://www.zotero.org/groups/1/chnm

It's empty, though, so might be best to remove it altogether.

**Comment by kstinso** [comment]
Okay, I think I covered this? Let me know if I broke something or did it wrong!

Kris
________________________________
